# -*- coding: utf-8 -*-
"""Imagecompression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m37OWSXaMaLCaIwBmTLDeg2nw4_AZd4l
"""

import matplotlib.image as mplib 
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA

img = mplib.imread('/content/sample.png')
print(img.shape)
plt.imshow(img)



img_r = np.reshape(img, (288, 1728)) 

print(img_r.shape)

pca = PCA(16).fit(img_r) 
img_transformed = pca.transform(img_r) 
print(img_transformed.shape) 
print(np.sum(pca.explained_variance_ratio_) )

temp = pca.inverse_transform(img_transformed) 
print(temp.shape)
temp = np.reshape(temp, (288, 432 ,4)) 
print(temp.shape)

plt.imshow(temp)